backend:
  name: github
  repo: jvegaalbela-png/jvegaalbela-png.github.io
  branch: main
  base_url: https://sveltia-cms-auth.jvegaalbela.workers.dev

media_folder: public/blog-uploads
public_folder: /blog-uploads

collections:
  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    folder: src/content/blog
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Publish Date
        name: pubDate
        widget: datetime
      - label: Updated Date
        name: updatedDate
        widget: datetime
        required: false
      - label: Hero Image
        name: heroImage
        widget: image
        required: false
      - label: Tags
        name: tags
        widget: list
        default: []
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown